### ISSUE TITLE
CSS task (Videos 46-48)

### ISSUE THREAD

**Issue by mahmoudelhosarry** [B-N-U/Discussions#14]
🕒 Deadline: 3 am 10 Nov
📘 Task Description

Watch CSS videos from number 46 to 48 carefully.
After watching, write a simple report in English explaining what you understood from the videos.
You don’t need to make it long — just make sure you really explain what you learned in your own words.

**Comment by joowe-creator** [comment]
Done,
I ended the CSS but the latest video is 47 right I don't find any video after that 
I learned how to control the elements with grid and how to make it responsive

**Comment by Amaryasser56** [comment]
I watched the 46 and 47 videos i didn't find the 48 one i learned how to display elements with grid and how to responsive the project in all screens

**Comment by mtarekkk** [comment]
I learned how to use CSS Gridbox to build clean, organized layouts. I learned things like grid-template-columns, gap, grid-template-rows.
I also learned about responsive design using media queries and flexible units so the layout looks good on any screen.

**Comment by mahmoudelhosarry** [comment]
Also watch video number 45, sorry it's my fault
@joowe-creator @mtarekkk @Amaryasser56

**Comment by omarghandour** [comment]
> Also watch video number 45, sorry it's my fault
> @joowe-creator @mtarekkk @Amaryasser56 

Why no response? 
@joowe-creator @mtarekkk @Amaryasser56

**Comment by joowe-creator** [comment]
We have finished the video number 45 in the last task and in this task we finished 46 and 47 I think we finished the CSS
@omarghandour

**Comment by mahmoudelhosarry** [comment]
My bad , I didn't realise that,
But doest that mean that you already done the project that in the video number 48? 
If so push it on GitHub and mention me ,

Also keep in mind keep the fast responses as possible . 
Thank you. 
@joowe-creator @mtarekkk @Amaryasser56

**Comment by joowe-creator** [comment]
Done, 
I finished the task of video number 48 
https://github.com/B-H-U/responsive-task.git this is the link of code 
@mahmoudelhosarry @omarghandour

**Comment by mtarekkk** [comment]
I get it, 
But can i just extend the deadline for tommorow because i am not home now and i don't have my laptop to make the code.
@omarghandour @mahmoudelhosarry

**Comment by mahmoudelhosarry** [comment]
I’m honestly confused you said you’d completed all the videos, but the project still isn’t done. One of you just finished, and another is asking for more time. So how could you say you were done in the first place?
@joowe-creator 
@mtarekkk

**Comment by mtarekkk** [comment]
I am done but i didn't know that i should send the code here and now i am not home so i am just asking for more time until i send the code from my laptop
@mahmoudelhosarry

**Comment by joowe-creator** [comment]
Engineer, I don't understand what the problem is. You were asking us in the first task to watch the videos, but it wasn't in Video 48, the last video of CSS 47. Then you said that it was your mistake to watch Video 45, so we were sincere now. You asked to do the task after the last video, and I did it and sent it. Where is the problem?
@mahmoudelhosarry

**Comment by Amaryasser56** [comment]
done this the task link https://github.com/B-N-U/task45.git 
@mahmoudelhosarry

**Comment by mtarekkk** [comment]
Done.
https://github.com/mtarekkk/Responsive-Form
